# Promp config
. $HOME/dotfiles/cmd/prompt

# Enable Git Tab Autocomplete
. $HOME/dotfiles/cmd/compgit

# Set history size
. $HOME/dotfiles/cmd/historysize

# Command Alias
. $HOME/dotfiles/cmd/ls

# Setup bin path
. $HOME/dotfiles/bin/export_path

# Setup nvm path
. $HOME/dotfiles/nvm/export_path

# Setup go path
. $HOME/dotfiles/go/export_path