autoload -Uz colors && colors
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats " %{$fg[green]%}(%b)%{$reset_color%}"

precmd() {
    vcs_info
}

setopt prompt_subst
PROMPT='%{$fg[red]%}[%*]%{$reset_color%} %2~${vcs_info_msg_0_} %# '

autoload -Uz compinit && compinit
autoload -Uz +X bashcompinit && bashcompinit

export HISTSIZE=100000 # default: 1000 as per zsh 5.8 on macOS
export SAVEHIST=$HISTSIZE

# Setup bin path
. $HOME/dotfiles/bin/export_path

# Setup nvm path
. $HOME/dotfiles/nvm/export_path

# Setup go path
. $HOME/dotfiles/go/export_path